# Generated by Django 5.0.2 on 2024-02-12 19:59

import django.core.validators
import django.db.models.deletion
import fruitipediaapp.profiles.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(limit_value=2), fruitipediaapp.profiles.validators.first_letter_validator])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(limit_value=1), fruitipediaapp.profiles.validators.first_letter_validator])),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('password', models.CharField(help_text='*Password length requirements: 8 to 20 characters', max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=8)])),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='')),
                ('age', models.PositiveSmallIntegerField(blank=True, default=18, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
